### ISSUE TITLE
register in `General` ?

### ISSUE THREAD

**Issue by t-bltg** [JuliaGeometry/QuadricMeshSimplification.jl#1]
Following https://github.com/JuliaGeometry/MarchingCubes.jl/issues/21#issuecomment-1836083638.

@sjkelly, in order to propose an example of mesh simplification in https://github.com/JuliaGeometry/MarchingCubes.jl/issues/23, would it be convenient to register this package ?

**Comment by sjkelly** [comment]
I don't think this ever properly worked

**Comment by t-bltg** [comment]
Thanks !
